### ISSUE TITLE
Use Bluetooth Proxy in Home Assistant to extend range?

### ISSUE THREAD

**Issue by snipah** [fl4p/batmon-ha#173]
No bug, but rather a feature request: Is it possible to use a bluetooth proxy for batmon-ha? I operate a smart camper but to save energy I switched moved my Home Assistant instance to my Unraid-Server and just pull all data from my Camper by using a Wireguard-Tunnel: This way I can get the data from an ESP32. My idea: Could I keep using batmon by using BT proxy (https://esphome.io/components/bluetooth_proxy.html)?

**Comment by fl4p** [comment]
technically it is possible to use the esphome BT proxy. however, since batmon uses bleak (which abstracts linux BlueZ stack) and not the HA BT component. I have not verified this.
It needs some changes, which shouldn’t be too hard. The best way I think would be if someone writes a bleak backend for the HA/ESPhome BT component.

Alternatively, run batmon on ESPhome using micropython, which needs implementing a bleak backend for MicroPython BT stack as well.

**Comment by fl4p** [comment]
dupe https://github.com/fl4p/batmon-ha/issues/34

**Comment by dowermyr** [comment]
I see this is closed. Does the esp32 bluetooth proxy work? What to fill in the "adapter" row to make it work?
