### ISSUE TITLE
Error Warnings

### ISSUE THREAD

**Issue by nuvolare12** [fl4p/batmon-ha#31]
Hello, i'm trying to connect with your Batmon-ha, but i've some errors, and i don't know if the error are from configuration or from the connection to the bms or Victron.
Could you check it
`WARNING  [mqtt_util.py:102] mqtt publish battery1/temperatures/1 failed: 4 (4, 1319)
INFO     [sampling.py:68] battery1 volt=3288,3291,3291,3291,3291,3290,3290,3288,3289,3290,3292,3289,3287,3287,3297,3686 temp=[22]
INFO     [sampling.py:93] DalyBt(40:16:09:01:58:4D) times: connect=0.00s fetch=0.92s
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/total_voltage failed: 4 (4, 1320)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/current failed: 4 (4, 1321)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/balance_current failed: 4 (4, 1322)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/soc_percent failed: 4 (4, 1323)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/power failed: 4 (4, 1324)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/capacity failed: 4 (4, 1325)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/cycle_capacity failed: 4 (4, 1326)
WARNING  [mqtt_util.py:102] mqtt publish battery1/mosfet_status/capacity_ah failed: 4 (4, 1327)
WARNING  [mqtt_util.py:102] mqtt publish battery1/mosfet_status/temperature failed: 4 (4, 1328)
INFO     [sampling.py:61] battery1 result@2022-11-01T16:23:38.028242 BmsSample(U=52.6V,I=0.00A,P=0W,q=230.0Ah/230.0,mos=nan°C)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/1 failed: 4 (4, 1329)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/2 failed: 4 (4, 1330)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/3 failed: 4 (4, 1331)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/4 failed: 4 (4, 1332)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/5 failed: 4 (4, 1333)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/6 failed: 4 (4, 1334)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/7 failed: 4 (4, 1335)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/8 failed: 4 (4, 1336)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/9 failed: 4 (4, 1337)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/10 failed: 4 (4, 1338)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/11 failed: 4 (4, 1339)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/12 failed: 4 (4, 1340)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/13 failed: 4 (4, 1341)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/14 failed: 4 (4, 1342)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/15 failed: 4 (4, 1343)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/16 failed: 4 (4, 1344)
WARNING  [mqtt_util.py:102] mqtt publish battery1/temperatures/1 failed: 4 (4, 1345)
INFO     [sampling.py:68] battery1 volt=3288,3290,3290,3290,3290,3290,3290,3288,3288,3290,3288,3288,3286,3286,3296,3280 temp=[22]
INFO     [sampling.py:93] DalyBt(40:16:09:01:58:4D) times: connect=0.00s fetch=0.93s
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/total_voltage failed: 4 (4, 1346)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/current failed: 4 (4, 1347)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/balance_current failed: 4 (4, 1348)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/soc_percent failed: 4 (4, 1349)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/power failed: 4 (4, 1350)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/capacity failed: 4 (4, 1351)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/cycle_capacity failed: 4 (4, 1352)
WARNING  [mqtt_util.py:102] mqtt publish battery1/mosfet_status/capacity_ah failed: 4 (4, 1353)
WARNING  [mqtt_util.py:102] mqtt publish battery1/mosfet_status/temperature failed: 4 (4, 1354)
INFO     [sampling.py:61] battery1 result@2022-11-01T16:23:39.964636 BmsSample(U=53.1V,I=0.00A,P=0W,q=230.0Ah/230.0,mos=nan°C)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/1 failed: 4 (4, 1355)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/2 failed: 4 (4, 1356)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/3 failed: 4 (4, 1357)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/4 failed: 4 (4, 1358)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/5 failed: 4 (4, 1359)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/6 failed: 4 (4, 1360)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/7 failed: 4 (4, 1361)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/8 failed: 4 (4, 1362)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/9 failed: 4 (4, 1363)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/10 failed: 4 (4, 1364)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/11 failed: 4 (4, 1365)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/12 failed: 4 (4, 1366)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/13 failed: 4 (4, 1367)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/14 failed: 4 (4, 1368)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/15 failed: 4 (4, 1369)
WARNING  [mqtt_util.py:102] mqtt publish battery1/cell_voltages/16 failed: 4 (4, 1370)
WARNING  [mqtt_util.py:102] mqtt publish battery1/temperatures/1 failed: 4 (4, 1371)
INFO     [sampling.py:68] battery1 volt=3289,3291,3291,3291,3291,3291,3291,3289,3289,3291,3293,3289,3287,3287,3297,3836 temp=[22]
INFO     [sampling.py:93] DalyBt(40:16:09:01:58:4D) times: connect=0.00s fetch=0.93s
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/total_voltage failed: 4 (4, 1372)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/current failed: 4 (4, 1373)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/balance_current failed: 4 (4, 1374)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/soc_percent failed: 4 (4, 1375)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/power failed: 4 (4, 1376)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/capacity failed: 4 (4, 1377)
WARNING  [mqtt_util.py:102] mqtt publish battery1/soc/cycle_capacity failed: 4 (4, 1378)
WARNING  [mqtt_util.py:102] mqtt publish battery1/mosfet_status/capacity_ah failed: 4 (4, 1379)
WARNING  [mqtt_util.py:102] mqtt publish battery1/mosfet_status/temperature failed: 4 (4, 1380)
INFO     [sampling.py:61] battery1 result@2022-11-01T16:23:41.897866 `

**Comment by fl4p** [comment]
Hi, seems like there is a connection issue to the MQTT broker (4=MQTT_ERR_NO_CONN)
Check mqtt host and credentials in the configuration

**Comment by TheBlackBGD** [comment]
Hello I also have erros with the Victron Shunt, i am not able to connect the Victron at all. can you please help. 

INFO     [victron.py:66] Pairing D7:3E:6F:C9:91:0E using psk '<281188>'...
INFO     [victron.py:59] Device D7:3E:6F:C9:91:0E asking for psk, giving 'None'
ERROR    [message_bus.py:623] got unexpected error processing a message: invalid literal for int() with base 10: '<281188>'.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus_next/message_bus.py", line 621, in _on_message
    self._process_message(msg)
  File "/usr/lib/python3.10/site-packages/dbus_next/message_bus.py", line 712, in _process_message
    handler(msg, send_reply)
  File "/usr/lib/python3.10/site-packages/dbus_next/message_bus.py", line 731, in handler
    result = method.fn(interface, *args)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/agent.py", line 258, in _request_passkey
    return int(passkey)
ValueError: invalid literal for int() with base 10: '<281188>'
ERROR    [client.py:617] Pairing /org/bluez/hci0/dev_D7_3E_6F_C9_91_0E with hci0 failed (org.bluez.Error.AuthenticationFailed)
INFO     [victron.py:68] Paired D7:3E:6F:C9:91:0E: False
ERROR    [main.py:85] Error (num 4) reading BMS: 
ERROR    [main.py:86] Stack: Traceback (most recent call last):
  File "/app/victron.py", line 73, in fetch_device
    data = await client.read_gatt_char(char['uuid'])
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 823, in read_gatt_char
    assert_reply(reply)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Connection Rejected Due To Security Reasons)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 81, in fetch_loop
    await fn()
  File "/app/main.py", line 146, in _fetch_victron
    result = await victron.fetch_device(dev['address'], psk=dev.get('pin'))
  File "/app/victron.py", line 64, in fetch_device
    async with BleakClient(address, handle_pairing=bool(psk)) as client:
  File "/usr/lib/python3.10/site-packages/bleak/backends/client.py", line 101, in __aexit__
    await self.disconnect()
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 539, in disconnect
    assert self._bus is None
AssertionError
INFO     [victron.py:63] Connecting D7:3E:6F:C9:91:0E to pair
ERROR    [main.py:85] Error (num 5) reading BMS: 
ERROR    [main.py:86] Stack: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus_next/aio/message_bus.py", line 305, in call
    await future
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 81, in fetch_loop
    await fn()
  File "/app/main.py", line 146, in _fetch_victron
    result = await victron.fetch_device(dev['address'], psk=dev.get('pin'))
  File "/app/victron.py", line 64, in fetch_device
    async with BleakClient(address, handle_pairing=bool(psk)) as client:
  File "/usr/lib/python3.10/site-packages/bleak/backends/client.py", line 97, in __aenter__
    await self.connect()
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 348, in connect
    reply = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by fl4p** [comment]
Please remove the <> symbols from the pin. It must be numeric

**Comment by TheBlackBGD** [comment]
Hello Again this is the error what i get : 
INFO     [victron.py:63] Connecting D7:3E:6F:C9:91:0E to pair
ERROR    [main.py:240] 1 exceptions occurred fetching BMSs
ERROR    [main.py:85] Error (num 4) reading BMS: 
ERROR    [main.py:86] Stack: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus_next/aio/message_bus.py", line 305, in call
    await future
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/main.py", line 81, in fetch_loop
    await fn()
  File "/app/main.py", line 241, in fn
    raise exceptions[0]
  File "/app/main.py", line 236, in fn
    await t
  File "/app/main.py", line 146, in _fetch_victron
    result = await victron.fetch_device(dev['address'], psk=dev.get('pin'))
  File "/app/victron.py", line 64, in fetch_device
    async with BleakClient(address, handle_pairing=bool(psk)) as client:
  File "/usr/lib/python3.10/site-packages/bleak/backends/client.py", line 97, in __aenter__
    await self.connect()
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 348, in connect
    reply = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
