### ISSUE TITLE
Add BMS controls

### ISSUE THREAD

**Issue by fl4p-old** [fl4p/batmon-ha#4]
* Toggle charge / discharge FET

JK : https://github.com/syssi/esphome-jk-bms/blob/main/components/jk_bms_ble/switch/jk_switch.cpp

**Comment by NeariX67** [comment]
## JBD

<details><summary>BMS has password</summary>

#### Test: Read write mode will fail because password is required

-> DD 5A 00 02 56 78 FF 30 77 
<- DD 00 81 00 00 00 77 (FAIL)

#### Enter Password (Password is 333333)

-> DD 5A 06 07 06 03 03 03 03 03 03 FF DB 77
<- DD 06 00 00 00 00 FF (OK)

##### Explanation:
[2] 06: Command Address
[3] 07: Data length
[4] 06: Password length
[5-10] 03: Password digit

Data length is 1 higher than password length

#### Read write mode

-> DD 5A 00 02 56 78 FF 30 77
<- DD 00 00 00 00 00 77 (OK)

</details>

<details><summary>BMS has no password</summary>

#### Read write mode

-> DD 5A 00 02 56 78 FF 30 77
<- DD 00 00 00 00 00 77 (OK)

</details>

**Comment by PMPoulsen** [comment]
I would love to see the Charge and Discharge controls for the FET's in JK BMS's implementad here. In this way HA could perform the logic controls of this function given knowledge of information on surplus PV power and decide on charging/discharge the battery.
I was looking into and ESP BTsolution when Istumbled over this great integration, keep up the good work.

**Comment by fl4p** [comment]
@NeariX67 thanks for posting the commands


Anyone knows how to implement a control switch for home assistant?
[the esp-home integration](https://github.com/syssi/esphome-jk-bms) uses a code gen function from esphome.

**Comment by fl4p** [comment]
In the dev branch https://github.com/fl4p/batmon-ha/tree/dev you'll find the add-on with switches working for JBD (tested) and jikong (untested)

**Comment by NeariX67** [comment]
Thanks, will test out!

**Comment by PMPoulsen** [comment]
Looking forward to a new release, I am not skilled enough to test your dev branch.

**Comment by dezfutak** [comment]
> In the dev branch https://github.com/fl4p/batmon-ha/tree/dev you'll find the add-on with switches working for JBD (tested) and jikong (untested)

What's the easiest way to test this out (Home Assistant newbie here :) )?

**Comment by fl4p** [comment]
The JK password protection is actually broken, because authentication is done by the App (the JK just sends the password in clear text and the app compares it to user input).
Did you try it while charging&discharging?
